CREATE EXTERNAL TABLE `gcdissuesnapshot` (
  `unix_time` bigint,
  `issue_id` bigint,
  `issue_number_raw` string,
  `issue_number` int,
  `publication_date` int,
  `price_raw` string,
  `price` array < string >,
  `page_count` int,
  `indicia_frequency` string,
  `isbn` string,
  `variant_name` string,
  `variant_of_issue_id` bigint,
  `barcode` string,
  `title` string,
  `on_sale_date` int,
  `rating` string,
  `volume_not_printed` boolean,
  `editing` array < string >,
  `notes` string,
  `created` int,
  `modified` int,
  `series_id` bigint,
  `series_name` string,
  `series_year_began` int,
  `series_year_ended` int,
  `series_is_current` boolean,
  `series_country_code` string,
  `series_language_code` string,
  `series_has_gallery` boolean,
  `series_is_comics_publication` boolean,
  `series_color` string,
  `series_dimensions` string,
  `series_paper_stock` string,
  `series_binding` array < string >,
  `series_publishing_format` string,
  `series_publishing_type` string,
  `series_is_singleton` boolean,
  `series_created` int,
  `series_modified` int,
  `publisher_id` bigint,
  `publisher_name` string,
  `publisher_country_code` string,
  `publisher_created` int,
  `publisher_modified` int,
  `publisher_url` string,
  `indicia_publisher_id` bigint,
  `indicia_publisher_name` string,
  `indicia_publisher_country_code` string,
  `indicia_publisher_parent_id` bigint,
  `indicia_publisher_year_began` int,
  `indicia_publisher_year_ended` int,
  `indicia_publisher_is_surrogate` boolean,
  `indicia_publisher_url` string,
  `indicia_publisher_created` int,
  `indicia_publisher_modified` int,
  `brand_id` bigint,
  `brand_name` string,
  `brand_url` string,
  `brand_created` int,
  `brand_modified` int,
  `story_id` bigint,
  `story_title` string,
  `story_feature` string,
  `story_sequence_number` int,
  `story_page_count` int,
  `story_script` array < string >,
  `story_pencils` array < string >,
  `story_inks` array < string >,
  `story_colors` array < string >,
  `story_letters` array < string >,
  `story_editing` array < string >,
  `story_genre` array < string >,
  `story_characters` array < string >,
  `story_type` string,
  `story_job_number` string,
  `story_first_line` string,
  `story_created` int,
  `story_modified` int
  )
PARTITIONED BY (
  `snapshot` int
  )
STORED AS PARQUET
LOCATION 's3://gcd-parquet/'
tblproperties ("parquet.compress"="SNAPPY");